/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.99
 * Generated at: 2024-05-04 03:02:14 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import modelo.Productos;
import modelo.Clientes;
import controller.CarritoBD;
import java.util.List;
import java.util.ArrayList;
import java.util.Date;
import java.text.SimpleDateFormat;
import java.text.ParseException;

public final class registrarproducto_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(3);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(8);
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("controller.CarritoBD");
    _jspx_imports_classes.add("java.util.Date");
    _jspx_imports_classes.add("java.text.SimpleDateFormat");
    _jspx_imports_classes.add("modelo.Productos");
    _jspx_imports_classes.add("modelo.Clientes");
    _jspx_imports_classes.add("java.text.ParseException");
    _jspx_imports_classes.add("java.util.ArrayList");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("    \r\n");
      out.write(" \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("	<head>\r\n");
      out.write("		<meta charset=\"ISO-8859-1\">\r\n");
      out.write("		<title>AÑADIR - CLIENTE </title>\r\n");
      out.write("		<link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css\" rel=\"stylesheet\" integrity=\"sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN\" crossorigin=\"anonymous\">\r\n");
      out.write("	</head>\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write(" ");

        HttpSession sesion = request.getSession();  
    
		CarritoBD ObjBD = new CarritoBD(); // CONTROLADOR
		Clientes   user = new  Clientes();		
				
		String ape = (String) request.getParameter   ("apellido");
		String name = (String) request.getParameter  ("nombre");
		String direc = (String) request.getParameter ("direc");
		String fec = (String) request.getParameter   ("fecnaci");
		String sexo = (String) request.getParameter("sexo");
		String correo = (String) request.getParameter("correo");
        String IdPass = (String) request.getParameter("password");		
		
        
        
        if (ape != null && !ape.isEmpty() &&
        	    name != null && !name.isEmpty() &&
        	    direc != null && !direc.isEmpty() &&
        	    fec != null && !fec.isEmpty() &&
        	    sexo != null && !sexo.isEmpty() &&
        	    correo != null && !correo.isEmpty() &&
        	    IdPass != null && !IdPass.isEmpty()) {
        	
            Clientes nuevo = new Clientes();
            
            nuevo.setApellidos(ape);
            nuevo.setNombres(name);
            nuevo.setDireccion(direc);
            
            SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
            Date fechaNacimiento = sdf.parse(fec);
            	
            nuevo.setFechaNacimiento(fec);
            
            char sexo1 = sexo.charAt(0);
            nuevo.setSexo(sexo1);
            nuevo.setCorreo(correo);
            nuevo.setPassword(IdPass);
            
            ObjBD.InsertarCliente(nuevo);        	
        	
        }

        
         
	
      out.write("	\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div class=\"container\">\r\n");
      out.write("    <div class=\"row justify-content-center\">\r\n");
      out.write("        <div class=\"col-md-6\">\r\n");
      out.write("            <h2 class=\"mt-5\">Registrar Cliente</h2>\r\n");
      out.write("            \r\n");
      out.write("            <form action=\"\" method=\"post\">\r\n");
      out.write("            \r\n");
      out.write("                <div class=\"mb-3\">\r\n");
      out.write("                    <label for=\"apellido\" class=\"form-label\">Apellidos:</label>\r\n");
      out.write("                    \r\n");
      out.write("                    <input type=\"text\" class=\"form-control\" name=\"apellido\" />\r\n");
      out.write("                                        \r\n");
      out.write("                </div>\r\n");
      out.write("                \r\n");
      out.write("                <div class=\"mb-3\">\r\n");
      out.write("                    <label for=\"nombre\" class=\"form-label\">Nombres:</label>\r\n");
      out.write("                    <input type=\"text\" class=\"form-control\"  name=\"nombre\" >\r\n");
      out.write("                </div>\r\n");
      out.write("                \r\n");
      out.write("                <div class=\"mb-3\">\r\n");
      out.write("                    <label for=\"direc\" class=\"form-label\">Dirección:</label>\r\n");
      out.write("                    <input type=\"text\" class=\"form-control\"  name=\"direc\" >\r\n");
      out.write("                </div>\r\n");
      out.write("                \r\n");
      out.write("                <div class=\"mb-3\">\r\n");
      out.write("                    <label for=\"fecnaci\" class=\"form-label\">Fecha de nacimiento:</label>\r\n");
      out.write("                    <input type=\"date\" class=\"form-control\"  name=\"fecnaci\" >\r\n");
      out.write("                </div>\r\n");
      out.write("                \r\n");
      out.write("                 <div class=\"mb-3\">\r\n");
      out.write("                    <label for=\"sexo\" class=\"form-label\">Sexo:</label>\r\n");
      out.write("                    <input type=\"text\" class=\"form-control\"  name=\"sexo\" >\r\n");
      out.write("                </div>\r\n");
      out.write("                \r\n");
      out.write("                 <div class=\"mb-3\">\r\n");
      out.write("                    <label for=\"correo\" class=\"form-label\">Correo:</label>\r\n");
      out.write("                    <input type=\"text\" class=\"form-control\"  name=\"correo\" >\r\n");
      out.write("                </div>\r\n");
      out.write("                \r\n");
      out.write("                <div class=\"mb-3\">\r\n");
      out.write("                    <label for=\"contraseña\" class=\"form-label\">Contraseña:</label>\r\n");
      out.write("                    <input type=\"password\" class=\"form-control\"  name=\"password\" >\r\n");
      out.write("                </div>\r\n");
      out.write("                \r\n");
      out.write("                <button type=\"submit\" class=\"btn btn-primary\"  value=\"registrar\">Registrar Cliente</button>\r\n");
      out.write("                               \r\n");
      out.write("            </form>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
